// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NexaWorks.Data;

#nullable disable

namespace NexaWorks.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260428072550_MigrationInitiale")]
    partial class MigrationInitiale
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NexaWorks.Models.Probleme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdProduit")
                        .HasColumnType("int");

                    b.Property<int>("IdStatut")
                        .HasColumnType("int");

                    b.Property<int>("IdSysteme")
                        .HasColumnType("int");

                    b.Property<int>("IdVersion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdProduit");

                    b.HasIndex("IdStatut");

                    b.HasIndex("IdSysteme");

                    b.HasIndex("IdVersion");

                    b.ToTable("Problemes");
                });

            modelBuilder.Entity("NexaWorks.Models.Produit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Produits");
                });

            modelBuilder.Entity("NexaWorks.Models.ProduitVersionSysteme", b =>
                {
                    b.Property<int>("IdProduit")
                        .HasColumnType("int");

                    b.Property<int>("IdVersion")
                        .HasColumnType("int");

                    b.Property<int>("IdSysteme")
                        .HasColumnType("int");

                    b.HasKey("IdProduit", "IdVersion", "IdSysteme");

                    b.HasIndex("IdSysteme");

                    b.HasIndex("IdVersion");

                    b.ToTable("ProduitsVersionsSystemes");
                });

            modelBuilder.Entity("NexaWorks.Models.Resolution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdProbleme")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdProbleme")
                        .IsUnique();

                    b.ToTable("Resolutions");
                });

            modelBuilder.Entity("NexaWorks.Models.Statut", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Statuts");
                });

            modelBuilder.Entity("NexaWorks.Models.Systeme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Systemes");
                });

            modelBuilder.Entity("NexaWorks.Models.Version", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Versions");
                });

            modelBuilder.Entity("NexaWorks.Models.Probleme", b =>
                {
                    b.HasOne("NexaWorks.Models.Produit", "Produit")
                        .WithMany("Problemes")
                        .HasForeignKey("IdProduit")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NexaWorks.Models.Statut", "Statut")
                        .WithMany("Problemes")
                        .HasForeignKey("IdStatut")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NexaWorks.Models.Systeme", "Systeme")
                        .WithMany("Problemes")
                        .HasForeignKey("IdSysteme")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NexaWorks.Models.Version", "Version")
                        .WithMany("Problemes")
                        .HasForeignKey("IdVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Produit");

                    b.Navigation("Statut");

                    b.Navigation("Systeme");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("NexaWorks.Models.ProduitVersionSysteme", b =>
                {
                    b.HasOne("NexaWorks.Models.Produit", "Produit")
                        .WithMany("ProduitsVersionsSystemes")
                        .HasForeignKey("IdProduit")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NexaWorks.Models.Systeme", "Systeme")
                        .WithMany("ProduitsVersionsSystemes")
                        .HasForeignKey("IdSysteme")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NexaWorks.Models.Version", "Version")
                        .WithMany("ProduitsVersionsSystemes")
                        .HasForeignKey("IdVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Produit");

                    b.Navigation("Systeme");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("NexaWorks.Models.Resolution", b =>
                {
                    b.HasOne("NexaWorks.Models.Probleme", "Probleme")
                        .WithOne("Resolution")
                        .HasForeignKey("NexaWorks.Models.Resolution", "IdProbleme")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Probleme");
                });

            modelBuilder.Entity("NexaWorks.Models.Probleme", b =>
                {
                    b.Navigation("Resolution");
                });

            modelBuilder.Entity("NexaWorks.Models.Produit", b =>
                {
                    b.Navigation("Problemes");

                    b.Navigation("ProduitsVersionsSystemes");
                });

            modelBuilder.Entity("NexaWorks.Models.Statut", b =>
                {
                    b.Navigation("Problemes");
                });

            modelBuilder.Entity("NexaWorks.Models.Systeme", b =>
                {
                    b.Navigation("Problemes");

                    b.Navigation("ProduitsVersionsSystemes");
                });

            modelBuilder.Entity("NexaWorks.Models.Version", b =>
                {
                    b.Navigation("Problemes");

                    b.Navigation("ProduitsVersionsSystemes");
                });
#pragma warning restore 612, 618
        }
    }
}
