// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NexaWorks.Data;

#nullable disable

namespace NexaWorks.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260428135357_MigrationSeedData")]
    partial class MigrationSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NexaWorks.Models.Probleme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdProduit")
                        .HasColumnType("int");

                    b.Property<int>("IdStatut")
                        .HasColumnType("int");

                    b.Property<int>("IdSysteme")
                        .HasColumnType("int");

                    b.Property<int>("IdVersion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdProduit");

                    b.HasIndex("IdStatut");

                    b.HasIndex("IdSysteme");

                    b.HasIndex("IdVersion");

                    b.ToTable("Problemes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "L’utilisateur signale que l’application affiche des soldes de portefeuille incohérents après la fermeture puis la réouverture de l’application : le solde affiché est parfois inférieur de plusieurs centaines d’euros par rapport au solde attendu.",
                            IdProduit = 1,
                            IdStatut = 2,
                            IdSysteme = 3,
                            IdVersion = 1
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2024, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "L’interface se fige plusieurs secondes à l’ouverture d’un portefeuille contenant plus de 500 positions, rendant l’application non réactive.",
                            IdProduit = 1,
                            IdStatut = 2,
                            IdSysteme = 2,
                            IdVersion = 2
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2024, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "La connexion OAuth échoue pour des comptes dont le nom d’utilisateur contient des caractères spéciaux, empêchant certains utilisateurs de se connecter.",
                            IdProduit = 1,
                            IdStatut = 2,
                            IdSysteme = 1,
                            IdVersion = 3
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "L’application se déconnecte de manière aléatoire après 30–45 minutes d’inactivité sur certains appareils, surtout ceux avec des politiques d’économie d’énergie agressives.",
                            IdProduit = 1,
                            IdStatut = 1,
                            IdSysteme = 4,
                            IdVersion = 3
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2024, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Les notifications push ne sont pas reçues lorsque des événements critiques sont envoyés depuis le backend.",
                            IdProduit = 1,
                            IdStatut = 2,
                            IdSysteme = 6,
                            IdVersion = 3
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lorsqu’un acheteur tente d’ajouter plusieurs articles à son panier en utilisant le bouton « Ajouter au panier », l’application ne met pas toujours à jour le nombre d’articles affiché dans le panier bien que les articles soient bien ajoutés en arrière‑plan, provoquant des erreurs d’achat.",
                            IdProduit = 1,
                            IdStatut = 1,
                            IdSysteme = 2,
                            IdVersion = 4
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2025, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "L’application consomme excessivement la batterie en arrière‑plan, ce qui provoque des retours négatifs des utilisateurs.",
                            IdProduit = 1,
                            IdStatut = 2,
                            IdSysteme = 4,
                            IdVersion = 4
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTime(2025, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Les favoris ajoutés sur un appareil iOS ne se synchronisent pas systématiquement sur les autres appareils de l’utilisateur, entraînant des pertes de favoris.",
                            IdProduit = 1,
                            IdStatut = 1,
                            IdSysteme = 5,
                            IdVersion = 4
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Les recherches de titres sont lentes et provoquent des timeouts sur des catalogues volumineux, rendant la fonctionnalité peu utilisable.",
                            IdProduit = 2,
                            IdStatut = 2,
                            IdSysteme = 2,
                            IdVersion = 1
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateTime(2024, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "L’application se ferme immédiatement lorsque l’utilisateur tente d’ouvrir un graphique montrant l’évolution d’une action sur plusieurs mois contenant un très grand nombre de points de données.",
                            IdProduit = 2,
                            IdStatut = 2,
                            IdSysteme = 4,
                            IdVersion = 5
                        },
                        new
                        {
                            Id = 11,
                            Date = new DateTime(2024, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Après rotation d’écran sur iPad, certains graphiques s’affichent mal ou leurs éléments sont mal repositionnés, altérant la lisibilité.",
                            IdProduit = 2,
                            IdStatut = 1,
                            IdSysteme = 5,
                            IdVersion = 5
                        },
                        new
                        {
                            Id = 12,
                            Date = new DateTime(2025, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lorsqu’un utilisateur importe un fichier contenant l’historique de ses transactions, certaines opérations apparaissent dans le désordre dans l’interface. Par exemple, une transaction du 12 janvier peut s’afficher avant une transaction du 10 janvier, ce qui rend la lecture de l’historique confuse.",
                            IdProduit = 2,
                            IdStatut = 1,
                            IdSysteme = 3,
                            IdVersion = 6
                        },
                        new
                        {
                            Id = 13,
                            Date = new DateTime(2025, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Certaines alertes sont envoyées en double à des utilisateurs, générant des notifications redondantes et du bruit.",
                            IdProduit = 2,
                            IdStatut = 1,
                            IdSysteme = 4,
                            IdVersion = 6
                        },
                        new
                        {
                            Id = 14,
                            Date = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "L’export CSV des transactions tronque les décimales sur certaines machines, entraînant des montants incorrects dans le fichier exporté.",
                            IdProduit = 2,
                            IdStatut = 2,
                            IdSysteme = 5,
                            IdVersion = 6
                        },
                        new
                        {
                            Id = 15,
                            Date = new DateTime(2024, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "L’export PDF des plans d’entraînement perd la mise en page sur certaines distributions Linux, rendant le document illisible.",
                            IdProduit = 3,
                            IdStatut = 2,
                            IdSysteme = 1,
                            IdVersion = 1
                        },
                        new
                        {
                            Id = 16,
                            Date = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Les rappels créés depuis l’application ne se matérialisent pas systématiquement dans l’application Calendrier MacOS pour certains comptes iCloud.",
                            IdProduit = 3,
                            IdStatut = 1,
                            IdSysteme = 2,
                            IdVersion = 2
                        },
                        new
                        {
                            Id = 17,
                            Date = new DateTime(2024, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "L’export CSV des séances contient des lignes dupliquées pour les utilisateurs situés dans des fuseaux horaires non UTC, faussant les rapports.",
                            IdProduit = 3,
                            IdStatut = 1,
                            IdSysteme = 3,
                            IdVersion = 2
                        },
                        new
                        {
                            Id = 18,
                            Date = new DateTime(2024, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Les préférences utilisateur ne sont pas sauvegardées après redémarrage de l’application, obligeant les utilisateurs à reconfigurer leurs paramètres.",
                            IdProduit = 3,
                            IdStatut = 2,
                            IdSysteme = 6,
                            IdVersion = 2
                        },
                        new
                        {
                            Id = 19,
                            Date = new DateTime(2025, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "La synchronisation Bluetooth avec certains capteurs se coupe après 10–15 minutes, interrompant les sessions de suivi.",
                            IdProduit = 3,
                            IdStatut = 1,
                            IdSysteme = 2,
                            IdVersion = 1
                        },
                        new
                        {
                            Id = 20,
                            Date = new DateTime(2025, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Les mesures cardio en session live sont affichées avec une latence de 5–10 secondes, ce qui nuit à l’expérience en temps réel.",
                            IdProduit = 3,
                            IdStatut = 1,
                            IdSysteme = 5,
                            IdVersion = 5
                        },
                        new
                        {
                            Id = 21,
                            Date = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Les exercices audio guidés se coupent prématurément sur certains PC, interrompant l’écoute des utilisateurs.",
                            IdProduit = 4,
                            IdStatut = 2,
                            IdSysteme = 3,
                            IdVersion = 1
                        },
                        new
                        {
                            Id = 22,
                            Date = new DateTime(2025, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Les notifications arrivent sans son malgré des réglages sonores activés, ce qui fait manquer des rappels aux utilisateurs.",
                            IdProduit = 4,
                            IdStatut = 2,
                            IdSysteme = 4,
                            IdVersion = 1
                        },
                        new
                        {
                            Id = 23,
                            Date = new DateTime(2025, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Le mode sombre n’est pas appliqué sur certaines vues de l’application, entraînant une incohérence visuelle.",
                            IdProduit = 4,
                            IdStatut = 1,
                            IdSysteme = 5,
                            IdVersion = 1
                        },
                        new
                        {
                            Id = 24,
                            Date = new DateTime(2025, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "L’export des journaux d’humeur laisse apparaître des métadonnées non anonymisées dans certains champs, posant un risque de non‑conformité RGPD.",
                            IdProduit = 4,
                            IdStatut = 1,
                            IdSysteme = 2,
                            IdVersion = 2
                        },
                        new
                        {
                            Id = 25,
                            Date = new DateTime(2025, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Les sessions de suivi supérieures à deux heures ne sont pas correctement enregistrées, entraînant une perte de données pour les longues sessions.",
                            IdProduit = 4,
                            IdStatut = 2,
                            IdSysteme = 3,
                            IdVersion = 2
                        });
                });

            modelBuilder.Entity("NexaWorks.Models.Produit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Produits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nom = "Trader en Herbe"
                        },
                        new
                        {
                            Id = 2,
                            Nom = "Maître des Investissements"
                        },
                        new
                        {
                            Id = 3,
                            Nom = "Planificateur d'Entraînement"
                        },
                        new
                        {
                            Id = 4,
                            Nom = "Planificateur d'Anxiété Sociale"
                        });
                });

            modelBuilder.Entity("NexaWorks.Models.ProduitVersionSysteme", b =>
                {
                    b.Property<int>("IdProduit")
                        .HasColumnType("int");

                    b.Property<int>("IdVersion")
                        .HasColumnType("int");

                    b.Property<int>("IdSysteme")
                        .HasColumnType("int");

                    b.HasKey("IdProduit", "IdVersion", "IdSysteme");

                    b.HasIndex("IdSysteme");

                    b.HasIndex("IdVersion");

                    b.ToTable("ProduitsVersionsSystemes");

                    b.HasData(
                        new
                        {
                            IdProduit = 1,
                            IdVersion = 1,
                            IdSysteme = 1
                        },
                        new
                        {
                            IdProduit = 1,
                            IdVersion = 1,
                            IdSysteme = 3
                        },
                        new
                        {
                            IdProduit = 1,
                            IdVersion = 2,
                            IdSysteme = 1
                        },
                        new
                        {
                            IdProduit = 1,
                            IdVersion = 2,
                            IdSysteme = 2
                        },
                        new
                        {
                            IdProduit = 1,
                            IdVersion = 2,
                            IdSysteme = 3
                        },
                        new
                        {
                            IdProduit = 1,
                            IdVersion = 3,
                            IdSysteme = 1
                        },
                        new
                        {
                            IdProduit = 1,
                            IdVersion = 3,
                            IdSysteme = 2
                        },
                        new
                        {
                            IdProduit = 1,
                            IdVersion = 3,
                            IdSysteme = 3
                        },
                        new
                        {
                            IdProduit = 1,
                            IdVersion = 3,
                            IdSysteme = 4
                        },
                        new
                        {
                            IdProduit = 1,
                            IdVersion = 3,
                            IdSysteme = 5
                        },
                        new
                        {
                            IdProduit = 1,
                            IdVersion = 3,
                            IdSysteme = 6
                        },
                        new
                        {
                            IdProduit = 1,
                            IdVersion = 4,
                            IdSysteme = 2
                        },
                        new
                        {
                            IdProduit = 1,
                            IdVersion = 4,
                            IdSysteme = 3
                        },
                        new
                        {
                            IdProduit = 1,
                            IdVersion = 4,
                            IdSysteme = 4
                        },
                        new
                        {
                            IdProduit = 1,
                            IdVersion = 4,
                            IdSysteme = 5
                        },
                        new
                        {
                            IdProduit = 2,
                            IdVersion = 1,
                            IdSysteme = 2
                        },
                        new
                        {
                            IdProduit = 2,
                            IdVersion = 1,
                            IdSysteme = 5
                        },
                        new
                        {
                            IdProduit = 2,
                            IdVersion = 5,
                            IdSysteme = 2
                        },
                        new
                        {
                            IdProduit = 2,
                            IdVersion = 5,
                            IdSysteme = 4
                        },
                        new
                        {
                            IdProduit = 2,
                            IdVersion = 5,
                            IdSysteme = 5
                        },
                        new
                        {
                            IdProduit = 2,
                            IdVersion = 6,
                            IdSysteme = 2
                        },
                        new
                        {
                            IdProduit = 2,
                            IdVersion = 6,
                            IdSysteme = 3
                        },
                        new
                        {
                            IdProduit = 2,
                            IdVersion = 6,
                            IdSysteme = 4
                        },
                        new
                        {
                            IdProduit = 2,
                            IdVersion = 6,
                            IdSysteme = 5
                        },
                        new
                        {
                            IdProduit = 3,
                            IdVersion = 1,
                            IdSysteme = 1
                        },
                        new
                        {
                            IdProduit = 3,
                            IdVersion = 1,
                            IdSysteme = 2
                        },
                        new
                        {
                            IdProduit = 3,
                            IdVersion = 2,
                            IdSysteme = 1
                        },
                        new
                        {
                            IdProduit = 3,
                            IdVersion = 2,
                            IdSysteme = 2
                        },
                        new
                        {
                            IdProduit = 3,
                            IdVersion = 2,
                            IdSysteme = 3
                        },
                        new
                        {
                            IdProduit = 3,
                            IdVersion = 2,
                            IdSysteme = 4
                        },
                        new
                        {
                            IdProduit = 3,
                            IdVersion = 2,
                            IdSysteme = 5
                        },
                        new
                        {
                            IdProduit = 3,
                            IdVersion = 2,
                            IdSysteme = 6
                        },
                        new
                        {
                            IdProduit = 3,
                            IdVersion = 5,
                            IdSysteme = 2
                        },
                        new
                        {
                            IdProduit = 3,
                            IdVersion = 5,
                            IdSysteme = 3
                        },
                        new
                        {
                            IdProduit = 3,
                            IdVersion = 5,
                            IdSysteme = 4
                        },
                        new
                        {
                            IdProduit = 3,
                            IdVersion = 5,
                            IdSysteme = 5
                        },
                        new
                        {
                            IdProduit = 4,
                            IdVersion = 1,
                            IdSysteme = 2
                        },
                        new
                        {
                            IdProduit = 4,
                            IdVersion = 1,
                            IdSysteme = 3
                        },
                        new
                        {
                            IdProduit = 4,
                            IdVersion = 1,
                            IdSysteme = 4
                        },
                        new
                        {
                            IdProduit = 4,
                            IdVersion = 1,
                            IdSysteme = 5
                        },
                        new
                        {
                            IdProduit = 4,
                            IdVersion = 2,
                            IdSysteme = 2
                        },
                        new
                        {
                            IdProduit = 4,
                            IdVersion = 2,
                            IdSysteme = 3
                        },
                        new
                        {
                            IdProduit = 4,
                            IdVersion = 2,
                            IdSysteme = 4
                        },
                        new
                        {
                            IdProduit = 4,
                            IdVersion = 2,
                            IdSysteme = 5
                        });
                });

            modelBuilder.Entity("NexaWorks.Models.Resolution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdProbleme")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdProbleme")
                        .IsUnique();

                    b.ToTable("Resolutions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Correction de la manière dont l’application sauvegarde les données avant de se fermer. Ajout d’une vérification au démarrage pour s’assurer que les informations affichées correspondent bien à celles enregistrées. Ainsi, le solde reste correct même après un redémarrage.",
                            IdProbleme = 1
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2024, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Modification du chargement des données pour que l’application n’essaie plus d’afficher tout d’un coup. Elle charge maintenant les informations petit à petit, ce qui évite les blocages et rend l’interface fluide.",
                            IdProbleme = 2
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2024, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Correction de la manière dont l’application envoie les informations de connexion. Les caractères spéciaux sont maintenant correctement pris en compte, ce qui permet à tous les utilisateurs de se connecter normalement.",
                            IdProbleme = 3
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2024, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Correction de la configuration du système de notifications et réinitialisation des paramètres liés aux notifications pour éviter les erreurs.",
                            IdProbleme = 5
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Réduction de la fréquence des tâches exécutées en arrière‑plan et optimisation de la manière dont l’application récupère les informations. Cela diminue fortement la consommation de la batterie.",
                            IdProbleme = 7
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2024, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Optimisation de la recherche en améliorant la manière dont les données sont récupérées. Les résultats s’affichent maintenant beaucoup plus rapidement, même avec de gros volumes.",
                            IdProbleme = 9
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2024, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Réduction de la quantité de données chargées d’un seul coup pour éviter que l’application ne dépasse la mémoire disponible. Le graphique s’ouvre maintenant sans faire planter l’application.",
                            IdProbleme = 10
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTime(2025, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Correction du format d’export pour que les montants conservent toujours leurs décimales, peu importe la configuration de l’ordinateur. Les fichiers CSV sont maintenant fiables.",
                            IdProbleme = 14
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateTime(2024, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Mise à jour de la bibliothèque de génération PDF et ajustement de la mise en page pour qu’elle reste correcte sur toutes les distributions Linux. Les documents exportés sont maintenant lisibles.",
                            IdProbleme = 15
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateTime(2024, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Correction de l’enregistrement des préférences pour qu’elles soient bien conservées après la fermeture de l’application. Les utilisateurs n’ont plus besoin de reconfigurer leurs paramètres.",
                            IdProbleme = 18
                        },
                        new
                        {
                            Id = 11,
                            Date = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Amélioration de la gestion de la lecture audio pour éviter les coupures. Les exercices peuvent maintenant être écoutés jusqu’au bout sans interruption.",
                            IdProbleme = 21
                        },
                        new
                        {
                            Id = 12,
                            Date = new DateTime(2025, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Correction des réglages des notifications pour que le son soit bien activé. Les utilisateurs entendent maintenant leurs alertes normalement.",
                            IdProbleme = 22
                        },
                        new
                        {
                            Id = 13,
                            Date = new DateTime(2025, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Correction de la manière dont les longues sessions sont sauvegardées pour éviter les pertes de données. Les sessions de plus de deux heures sont maintenant enregistrées correctement.",
                            IdProbleme = 25
                        });
                });

            modelBuilder.Entity("NexaWorks.Models.Statut", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Statuts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nom = "En cours"
                        },
                        new
                        {
                            Id = 2,
                            Nom = "Résolu"
                        });
                });

            modelBuilder.Entity("NexaWorks.Models.Systeme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Systemes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nom = "Linux"
                        },
                        new
                        {
                            Id = 2,
                            Nom = "MacOS"
                        },
                        new
                        {
                            Id = 3,
                            Nom = "Windows"
                        },
                        new
                        {
                            Id = 4,
                            Nom = "Android"
                        },
                        new
                        {
                            Id = 5,
                            Nom = "iOS"
                        },
                        new
                        {
                            Id = 6,
                            Nom = "Windows Mobile"
                        });
                });

            modelBuilder.Entity("NexaWorks.Models.Version", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Versions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Numero = "1.0"
                        },
                        new
                        {
                            Id = 2,
                            Numero = "1.1"
                        },
                        new
                        {
                            Id = 3,
                            Numero = "1.2"
                        },
                        new
                        {
                            Id = 4,
                            Numero = "1.3"
                        },
                        new
                        {
                            Id = 5,
                            Numero = "2.0"
                        },
                        new
                        {
                            Id = 6,
                            Numero = "2.1"
                        });
                });

            modelBuilder.Entity("NexaWorks.Models.Probleme", b =>
                {
                    b.HasOne("NexaWorks.Models.Produit", "Produit")
                        .WithMany("Problemes")
                        .HasForeignKey("IdProduit")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NexaWorks.Models.Statut", "Statut")
                        .WithMany("Problemes")
                        .HasForeignKey("IdStatut")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NexaWorks.Models.Systeme", "Systeme")
                        .WithMany("Problemes")
                        .HasForeignKey("IdSysteme")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NexaWorks.Models.Version", "Version")
                        .WithMany("Problemes")
                        .HasForeignKey("IdVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Produit");

                    b.Navigation("Statut");

                    b.Navigation("Systeme");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("NexaWorks.Models.ProduitVersionSysteme", b =>
                {
                    b.HasOne("NexaWorks.Models.Produit", "Produit")
                        .WithMany("ProduitsVersionsSystemes")
                        .HasForeignKey("IdProduit")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NexaWorks.Models.Systeme", "Systeme")
                        .WithMany("ProduitsVersionsSystemes")
                        .HasForeignKey("IdSysteme")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NexaWorks.Models.Version", "Version")
                        .WithMany("ProduitsVersionsSystemes")
                        .HasForeignKey("IdVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Produit");

                    b.Navigation("Systeme");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("NexaWorks.Models.Resolution", b =>
                {
                    b.HasOne("NexaWorks.Models.Probleme", "Probleme")
                        .WithOne("Resolution")
                        .HasForeignKey("NexaWorks.Models.Resolution", "IdProbleme")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Probleme");
                });

            modelBuilder.Entity("NexaWorks.Models.Probleme", b =>
                {
                    b.Navigation("Resolution");
                });

            modelBuilder.Entity("NexaWorks.Models.Produit", b =>
                {
                    b.Navigation("Problemes");

                    b.Navigation("ProduitsVersionsSystemes");
                });

            modelBuilder.Entity("NexaWorks.Models.Statut", b =>
                {
                    b.Navigation("Problemes");
                });

            modelBuilder.Entity("NexaWorks.Models.Systeme", b =>
                {
                    b.Navigation("Problemes");

                    b.Navigation("ProduitsVersionsSystemes");
                });

            modelBuilder.Entity("NexaWorks.Models.Version", b =>
                {
                    b.Navigation("Problemes");

                    b.Navigation("ProduitsVersionsSystemes");
                });
#pragma warning restore 612, 618
        }
    }
}
